name: "the caller"

on:
    workflow_dispatch:
      inputs:
        # environment:
        #   description: 'Environment to deploy to'
        #   required: true
        #   default: 'dev'

jobs:

  dev:
    name: "job-dev (${{ matrix.instance.name }})"        
    strategy: 
        fail-fast: false
        matrix:
            instance:
                - name: foo
                  app-env: dev
    uses: AVitg/wf_test/.github/workflows/random_reusable_workflow.yaml@main
    with:      
      app-env: "${{ matrix.instance.app-env }}"

  anotherJOB:
    name: "job-preprod (${{ matrix.instance.name }})"
    needs: dev
    strategy: 
        fail-fast: false
        matrix:
            instance:
                - name: foo
                  app-env: preprod
    uses: AVitg/wf_test/.github/workflows/random_reusable_workflow.yaml@main
    with:      
      app-env: "${{ matrix.instance.app-env }}"


  jetanotherJOB:
    needs: anotherJOB
    name: "job-prod (${{ matrix.instance.name }})"
    strategy: 
        fail-fast: false
        matrix:
            instance:
                - name: foo
                  app-env: prod
    uses: AVitg/wf_test/.github/workflows/random_reusable_workflow.yaml@main
    with:      
      app-env: "${{ matrix.instance.app-env }}"