name: "the caller"

on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'Environment to deploy to'
          required: true
          default: 'dev'

jobs:

  dev:
    name: "job-dev (${{ matrix.instance.name }})"        
    strategy: 
        fail-fast: false
    uses: AVitg/wf_test/.github/workflows/random_reusable_workflow.yaml@main
    with:      
      dispatch-environment: ${{ github.event.inputs.environment || '' }}

  anotherJOB:
    name: "job-preprod (${{ matrix.instance.name }})"
    needs: dev
    strategy: 
        fail-fast: false        
    uses: AVitg/wf_test/.github/workflows/random_reusable_workflow.yaml@main
    with:      
      dispatch-environment: ${{ github.event.inputs.environment || '' }}


  jetanotherJOB:
    needs: anotherJOB
    name: "job-prod (${{ matrix.instance.name }})"
    strategy: 
        fail-fast: false        
    uses: AVitg/wf_test/.github/workflows/random_reusable_workflow.yaml@main
    with:      
      dispatch-environment: ${{ github.event.inputs.environment || '' }}