name: "the caller"

on:
    workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'preprod'

jobs:
  preprod:
    name: "PreProd (${{ matrix.instance.name }})"
    strategy: 
        fail-fast: false
        matrix:
            instance:
                - name: foo
                  app-env: preprod
    uses: AVitg/wf_test/.github/workflows/random_reusable_workflow.yaml@main
    with:      
      app-env: "${{ matrix.instance.app-env }}"
