name: "my random workflow"
on: 
    workflow_call:
     inputs:      
      dispatch-environment:
        required: true
        type: string
      has-dev:
        type: boolean
        default: false
      has-preprod:
        type: boolean
        default: false
      has-prod:
        type: boolean
        default: false


jobs: 
  setup:
    runs-on: ubuntu-slim
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
      has_envs: ${{ steps.build-matrix.outputs.has_envs }}
    steps:
      - name: Build deployment matrix
        id: build-matrix
        run: |
          ENVS='[]'
          APP_PATH="${{ inputs.dispatch-environment }}"

          add_env() {
            local ENV_NAME=$1                      

            if [[ "$ENV_NAME" == "prod" ]]; then
              echo ("PROD")
            fi
            if [[ "$ENV_NAME" == "dev" ]]; then
              echo ("DEV")
            fi
            if [[ "$ENV_NAME" == "preprod" ]]; then
              echo ("PRE-PROD")
            fi
          } 
          
          



  randomsomething:
        environment: ${{ inputs.dispatch-environment }}
        runs-on: ubuntu-slim
        steps:
          - name: Checkout Code
            uses: actions/checkout@v6
            with:
              fetch-depth: 0 

          - name: Set up Python environment
            run: |
              echo "Setting up Python environment" 
              pip install -r script/requirements.txt

          - name: run python
            run: |               
              echo "Running script: $script"
              ENV=${{ inputs.dispatch-environment }} python3 script/main.py
